/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia5_2;

import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Lissette
 */
public class NivelExperiencia extends javax.swing.JFrame {

    /**
     * Creates new form NivelExperiencia
     */
    public NivelExperiencia() {
        initComponents();
        ButtonGroup grupoExperiencia = new ButtonGroup();
        grupoExperiencia.add(jRadioButtonPrincipiante);
        grupoExperiencia.add(jRadioButtonIntermedio);
        grupoExperiencia.add(jRadioButtonAvanzado);
        
        configurarEventos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButtonPrincipiante = new javax.swing.JRadioButton();
        jRadioButtonIntermedio = new javax.swing.JRadioButton();
        jRadioButtonAvanzado = new javax.swing.JRadioButton();
        jButtonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nivel de experiencia en Java:");

        jRadioButtonPrincipiante.setText("Principiante");

        jRadioButtonIntermedio.setText("Intermedio");

        jRadioButtonAvanzado.setText("Avanzado");

        jButtonConfirmar.setText("Confirmar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAvanzado)
                            .addComponent(jRadioButtonIntermedio)
                            .addComponent(jRadioButtonPrincipiante)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButtonConfirmar)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPrincipiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonIntermedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonAvanzado)
                .addGap(30, 30, 30)
                .addComponent(jButtonConfirmar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelExperiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelExperiencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonAvanzado;
    private javax.swing.JRadioButton jRadioButtonIntermedio;
    private javax.swing.JRadioButton jRadioButtonPrincipiante;
    // End of variables declaration//GEN-END:variables

    
    private void configurarEventos(){
    jButtonConfirmar.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent evt){
            if(jRadioButtonPrincipiante.isSelected()){
                JOptionPane.showMessageDialog(rootPane, "Seleccionaste nivel principiante");
            }else if(jRadioButtonIntermedio.isSelected()){
                JOptionPane.showMessageDialog(rootPane, "Seleccionaste nivel intermedio");
            }else if(jRadioButtonAvanzado.isSelected()){
                JOptionPane.showMessageDialog(rootPane, "Seleccionaste nivel avanzado");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un nivel");
            }
        }
    });
}


}
